# Generated by Django 3.2.8 on 2021-10-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0002_remove_styletransfermodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styletransfermodel',
            name='img',
            field=models.ImageField(upload_to='content-images/'),
        ),
    ]
