# Generated by Django 3.2.8 on 2021-10-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0003_alter_styletransfermodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='output-images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='StyleTransferModel',
            new_name='ContentImagesModel',
        ),
    ]
