# Generated by Django 3.2.8 on 2021-10-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0004_auto_20211027_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputimagesmodel',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
