# Generated by Django 3.2.8 on 2021-10-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0005_alter_outputimagesmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputimagesmodel',
            name='img',
            field=models.ImageField(upload_to='output-images/'),
        ),
    ]
