# Generated by Django 3.2.8 on 2021-10-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0007_styleimagesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styleimagesmodel',
            name='name',
        ),
    ]
