# Generated by Django 3.2.8 on 2021-11-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0008_remove_styleimagesmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleimagesmodel',
            name='name',
            field=models.CharField(default='style_image', max_length=50),
        ),
    ]
